// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: delivery-pkg-service.proto

package delivery_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryUuid  []byte                 `protobuf:"bytes,1,opt,name=delivery_uuid,json=deliveryUuid,proto3" json:"delivery_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryGetReq) Reset() {
	*x = DeliveryGetReq{}
	mi := &file_delivery_pkg_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryGetReq) ProtoMessage() {}

func (x *DeliveryGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_pkg_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryGetReq.ProtoReflect.Descriptor instead.
func (*DeliveryGetReq) Descriptor() ([]byte, []int) {
	return file_delivery_pkg_service_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryGetReq) GetDeliveryUuid() []byte {
	if x != nil {
		return x.DeliveryUuid
	}
	return nil
}

type DeliveryDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryUuid  []byte                 `protobuf:"bytes,1,opt,name=delivery_uuid,json=deliveryUuid,proto3" json:"delivery_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryDeleteReq) Reset() {
	*x = DeliveryDeleteReq{}
	mi := &file_delivery_pkg_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryDeleteReq) ProtoMessage() {}

func (x *DeliveryDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_pkg_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryDeleteReq.ProtoReflect.Descriptor instead.
func (*DeliveryDeleteReq) Descriptor() ([]byte, []int) {
	return file_delivery_pkg_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryDeleteReq) GetDeliveryUuid() []byte {
	if x != nil {
		return x.DeliveryUuid
	}
	return nil
}

type EmptyDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyDelivery) Reset() {
	*x = EmptyDelivery{}
	mi := &file_delivery_pkg_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyDelivery) ProtoMessage() {}

func (x *EmptyDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_pkg_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyDelivery.ProtoReflect.Descriptor instead.
func (*EmptyDelivery) Descriptor() ([]byte, []int) {
	return file_delivery_pkg_service_proto_rawDescGZIP(), []int{2}
}

var File_delivery_pkg_service_proto protoreflect.FileDescriptor

const file_delivery_pkg_service_proto_rawDesc = "" +
	"\n" +
	"\x1adelivery-pkg-service.proto\x12\x06models\x1a\x19delivery-pkg-models.proto\"5\n" +
	"\x0eDeliveryGetReq\x12#\n" +
	"\rdelivery_uuid\x18\x01 \x01(\fR\fdeliveryUuid\"8\n" +
	"\x11DeliveryDeleteReq\x12#\n" +
	"\rdelivery_uuid\x18\x01 \x01(\fR\fdeliveryUuid\"\x0f\n" +
	"\rEmptyDelivery2\x8e\x02\n" +
	"\x0fDeliveryService\x12A\n" +
	"\x16CreateOrUpdateDelivery\x12\x10.models.Delivery\x1a\x15.models.EmptyDelivery\x12:\n" +
	"\rGetDeliveries\x12\x15.models.EmptyDelivery\x1a\x12.models.Deliveries\x128\n" +
	"\fDeliveryById\x12\x16.models.DeliveryGetReq\x1a\x10.models.Delivery\x12B\n" +
	"\x0eDeleteDelivery\x12\x19.models.DeliveryDeleteReq\x1a\x15.models.EmptyDeliveryB\x18Z\x16protocols/delivery-pkgb\x06proto3"

var (
	file_delivery_pkg_service_proto_rawDescOnce sync.Once
	file_delivery_pkg_service_proto_rawDescData []byte
)

func file_delivery_pkg_service_proto_rawDescGZIP() []byte {
	file_delivery_pkg_service_proto_rawDescOnce.Do(func() {
		file_delivery_pkg_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_pkg_service_proto_rawDesc), len(file_delivery_pkg_service_proto_rawDesc)))
	})
	return file_delivery_pkg_service_proto_rawDescData
}

var file_delivery_pkg_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_delivery_pkg_service_proto_goTypes = []any{
	(*DeliveryGetReq)(nil),    // 0: models.DeliveryGetReq
	(*DeliveryDeleteReq)(nil), // 1: models.DeliveryDeleteReq
	(*EmptyDelivery)(nil),     // 2: models.EmptyDelivery
	(*Delivery)(nil),          // 3: models.Delivery
	(*Deliveries)(nil),        // 4: models.Deliveries
}
var file_delivery_pkg_service_proto_depIdxs = []int32{
	3, // 0: models.DeliveryService.CreateOrUpdateDelivery:input_type -> models.Delivery
	2, // 1: models.DeliveryService.GetDeliveries:input_type -> models.EmptyDelivery
	0, // 2: models.DeliveryService.DeliveryById:input_type -> models.DeliveryGetReq
	1, // 3: models.DeliveryService.DeleteDelivery:input_type -> models.DeliveryDeleteReq
	2, // 4: models.DeliveryService.CreateOrUpdateDelivery:output_type -> models.EmptyDelivery
	4, // 5: models.DeliveryService.GetDeliveries:output_type -> models.Deliveries
	3, // 6: models.DeliveryService.DeliveryById:output_type -> models.Delivery
	2, // 7: models.DeliveryService.DeleteDelivery:output_type -> models.EmptyDelivery
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_delivery_pkg_service_proto_init() }
func file_delivery_pkg_service_proto_init() {
	if File_delivery_pkg_service_proto != nil {
		return
	}
	file_delivery_pkg_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_pkg_service_proto_rawDesc), len(file_delivery_pkg_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_pkg_service_proto_goTypes,
		DependencyIndexes: file_delivery_pkg_service_proto_depIdxs,
		MessageInfos:      file_delivery_pkg_service_proto_msgTypes,
	}.Build()
	File_delivery_pkg_service_proto = out.File
	file_delivery_pkg_service_proto_goTypes = nil
	file_delivery_pkg_service_proto_depIdxs = nil
}
