// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: delivery-pkg-models.proto

package delivery_pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Delivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryUuid  []byte                 `protobuf:"bytes,1,opt,name=delivery_uuid,json=deliveryUuid,proto3" json:"delivery_uuid,omitempty"`
	OrderUuid     []byte                 `protobuf:"bytes,2,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_delivery_pkg_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_pkg_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_delivery_pkg_models_proto_rawDescGZIP(), []int{0}
}

func (x *Delivery) GetDeliveryUuid() []byte {
	if x != nil {
		return x.DeliveryUuid
	}
	return nil
}

func (x *Delivery) GetOrderUuid() []byte {
	if x != nil {
		return x.OrderUuid
	}
	return nil
}

type Deliveries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deliveries    []*Delivery            `protobuf:"bytes,1,rep,name=Deliveries,proto3" json:"Deliveries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deliveries) Reset() {
	*x = Deliveries{}
	mi := &file_delivery_pkg_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deliveries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deliveries) ProtoMessage() {}

func (x *Deliveries) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_pkg_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deliveries.ProtoReflect.Descriptor instead.
func (*Deliveries) Descriptor() ([]byte, []int) {
	return file_delivery_pkg_models_proto_rawDescGZIP(), []int{1}
}

func (x *Deliveries) GetDeliveries() []*Delivery {
	if x != nil {
		return x.Deliveries
	}
	return nil
}

var File_delivery_pkg_models_proto protoreflect.FileDescriptor

const file_delivery_pkg_models_proto_rawDesc = "" +
	"\n" +
	"\x19delivery-pkg-models.proto\x12\x06models\"N\n" +
	"\bDelivery\x12#\n" +
	"\rdelivery_uuid\x18\x01 \x01(\fR\fdeliveryUuid\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x02 \x01(\fR\torderUuid\">\n" +
	"\n" +
	"Deliveries\x120\n" +
	"\n" +
	"Deliveries\x18\x01 \x03(\v2\x10.models.DeliveryR\n" +
	"DeliveriesB\x18Z\x16protocols/delivery-pkgb\x06proto3"

var (
	file_delivery_pkg_models_proto_rawDescOnce sync.Once
	file_delivery_pkg_models_proto_rawDescData []byte
)

func file_delivery_pkg_models_proto_rawDescGZIP() []byte {
	file_delivery_pkg_models_proto_rawDescOnce.Do(func() {
		file_delivery_pkg_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_pkg_models_proto_rawDesc), len(file_delivery_pkg_models_proto_rawDesc)))
	})
	return file_delivery_pkg_models_proto_rawDescData
}

var file_delivery_pkg_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_delivery_pkg_models_proto_goTypes = []any{
	(*Delivery)(nil),   // 0: models.Delivery
	(*Deliveries)(nil), // 1: models.Deliveries
}
var file_delivery_pkg_models_proto_depIdxs = []int32{
	0, // 0: models.Deliveries.Deliveries:type_name -> models.Delivery
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_delivery_pkg_models_proto_init() }
func file_delivery_pkg_models_proto_init() {
	if File_delivery_pkg_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_pkg_models_proto_rawDesc), len(file_delivery_pkg_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_delivery_pkg_models_proto_goTypes,
		DependencyIndexes: file_delivery_pkg_models_proto_depIdxs,
		MessageInfos:      file_delivery_pkg_models_proto_msgTypes,
	}.Build()
	File_delivery_pkg_models_proto = out.File
	file_delivery_pkg_models_proto_goTypes = nil
	file_delivery_pkg_models_proto_depIdxs = nil
}
