// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: delivery-pkg-service.proto

package delivery_pkg

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryService_CreateOrUpdateDelivery_FullMethodName = "/models.DeliveryService/CreateOrUpdateDelivery"
	DeliveryService_GetDeliveries_FullMethodName          = "/models.DeliveryService/GetDeliveries"
	DeliveryService_DeliveryByDeliUuid_FullMethodName     = "/models.DeliveryService/DeliveryByDeliUuid"
	DeliveryService_DeliveryByOrderUuid_FullMethodName    = "/models.DeliveryService/DeliveryByOrderUuid"
	DeliveryService_DeleteDelivery_FullMethodName         = "/models.DeliveryService/DeleteDelivery"
)

// DeliveryServiceClient is the client API for DeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeliveryServiceClient interface {
	CreateOrUpdateDelivery(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*EmptyDelivery, error)
	GetDeliveries(ctx context.Context, in *EmptyDelivery, opts ...grpc.CallOption) (*Deliveries, error)
	DeliveryByDeliUuid(ctx context.Context, in *DeliveryGetReq, opts ...grpc.CallOption) (*Delivery, error)
	DeliveryByOrderUuid(ctx context.Context, in *DeliveryGetReqByOrder, opts ...grpc.CallOption) (*Delivery, error)
	DeleteDelivery(ctx context.Context, in *DeliveryDeleteReq, opts ...grpc.CallOption) (*EmptyDelivery, error)
}

type deliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryServiceClient(cc grpc.ClientConnInterface) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) CreateOrUpdateDelivery(ctx context.Context, in *Delivery, opts ...grpc.CallOption) (*EmptyDelivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyDelivery)
	err := c.cc.Invoke(ctx, DeliveryService_CreateOrUpdateDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) GetDeliveries(ctx context.Context, in *EmptyDelivery, opts ...grpc.CallOption) (*Deliveries, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Deliveries)
	err := c.cc.Invoke(ctx, DeliveryService_GetDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) DeliveryByDeliUuid(ctx context.Context, in *DeliveryGetReq, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_DeliveryByDeliUuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) DeliveryByOrderUuid(ctx context.Context, in *DeliveryGetReqByOrder, opts ...grpc.CallOption) (*Delivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delivery)
	err := c.cc.Invoke(ctx, DeliveryService_DeliveryByOrderUuid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryServiceClient) DeleteDelivery(ctx context.Context, in *DeliveryDeleteReq, opts ...grpc.CallOption) (*EmptyDelivery, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyDelivery)
	err := c.cc.Invoke(ctx, DeliveryService_DeleteDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryServiceServer is the server API for DeliveryService service.
// All implementations must embed UnimplementedDeliveryServiceServer
// for forward compatibility.
type DeliveryServiceServer interface {
	CreateOrUpdateDelivery(context.Context, *Delivery) (*EmptyDelivery, error)
	GetDeliveries(context.Context, *EmptyDelivery) (*Deliveries, error)
	DeliveryByDeliUuid(context.Context, *DeliveryGetReq) (*Delivery, error)
	DeliveryByOrderUuid(context.Context, *DeliveryGetReqByOrder) (*Delivery, error)
	DeleteDelivery(context.Context, *DeliveryDeleteReq) (*EmptyDelivery, error)
	mustEmbedUnimplementedDeliveryServiceServer()
}

// UnimplementedDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryServiceServer struct{}

func (UnimplementedDeliveryServiceServer) CreateOrUpdateDelivery(context.Context, *Delivery) (*EmptyDelivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) GetDeliveries(context.Context, *EmptyDelivery) (*Deliveries, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveries not implemented")
}
func (UnimplementedDeliveryServiceServer) DeliveryByDeliUuid(context.Context, *DeliveryGetReq) (*Delivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliveryByDeliUuid not implemented")
}
func (UnimplementedDeliveryServiceServer) DeliveryByOrderUuid(context.Context, *DeliveryGetReqByOrder) (*Delivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliveryByOrderUuid not implemented")
}
func (UnimplementedDeliveryServiceServer) DeleteDelivery(context.Context, *DeliveryDeleteReq) (*EmptyDelivery, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDelivery not implemented")
}
func (UnimplementedDeliveryServiceServer) mustEmbedUnimplementedDeliveryServiceServer() {}
func (UnimplementedDeliveryServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryServiceServer will
// result in compilation errors.
type UnsafeDeliveryServiceServer interface {
	mustEmbedUnimplementedDeliveryServiceServer()
}

func RegisterDeliveryServiceServer(s grpc.ServiceRegistrar, srv DeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryService_ServiceDesc, srv)
}

func _DeliveryService_CreateOrUpdateDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).CreateOrUpdateDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_CreateOrUpdateDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).CreateOrUpdateDelivery(ctx, req.(*Delivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_GetDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyDelivery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).GetDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_GetDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).GetDeliveries(ctx, req.(*EmptyDelivery))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_DeliveryByDeliUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).DeliveryByDeliUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_DeliveryByDeliUuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).DeliveryByDeliUuid(ctx, req.(*DeliveryGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_DeliveryByOrderUuid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryGetReqByOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).DeliveryByOrderUuid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_DeliveryByOrderUuid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).DeliveryByOrderUuid(ctx, req.(*DeliveryGetReqByOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryService_DeleteDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliveryDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).DeleteDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryService_DeleteDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).DeleteDelivery(ctx, req.(*DeliveryDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryService_ServiceDesc is the grpc.ServiceDesc for DeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "models.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdateDelivery",
			Handler:    _DeliveryService_CreateOrUpdateDelivery_Handler,
		},
		{
			MethodName: "GetDeliveries",
			Handler:    _DeliveryService_GetDeliveries_Handler,
		},
		{
			MethodName: "DeliveryByDeliUuid",
			Handler:    _DeliveryService_DeliveryByDeliUuid_Handler,
		},
		{
			MethodName: "DeliveryByOrderUuid",
			Handler:    _DeliveryService_DeliveryByOrderUuid_Handler,
		},
		{
			MethodName: "DeleteDelivery",
			Handler:    _DeliveryService_DeleteDelivery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery-pkg-service.proto",
}
